"""V-FRM-05, V-FRM-08, V-FRM-09, V-FRM-10, V-ATT-01 — hand-computed frame anchors.

WHY THIS FILE EXISTS BEFORE THE IMPLEMENTATION
----------------------------------------------
The pre-implementation mathematical audit
(``docs/research/PRE_IMPLEMENTATION_MATHEMATICAL_AUDIT.md``) found a sign error in the
wind-frame composition, ``T_BW = R_y(-alpha) R_z(beta)``, that had been published in
RS-001 and had passed a quality gate.  It would have reversed every sideslip-dependent
side force and yawing moment.

The important part is *how it survived*: the round-trip test specified for it,
V-FRM-05, would have passed, because a builder and an extractor written to agree with
each other round-trip perfectly whether or not either is right.  A **uniformly applied
wrong convention is self-consistent**, and self-consistency is what most tests measure.

Only an expected value obtained from *outside* the implementation can catch that class
of error.  Hence this file, written before ``radius/frames/`` exists: every expected
value below is derived by hand from ``docs/methodology/NOTATION_AND_CONVENTIONS.md``
and encoded as a literal.  Nothing here is produced by the code under test.

RULES THIS FILE OBEYS (from the Phase 2A brief, and from the audit's findings)
-----------------------------------------------------------------------------
* No expected value is generated by the implementation.
* No test is a round trip only.
* ``T @ T.T == I`` is never the sole evidence of correctness — a wrong convention is
  orthonormal too.
* No comparison of one implementation path against another that shares a convention.
  Where two paths (Euler and quaternion) are both checked, each is compared against the
  *same hand-derived literal*, not against each other.
* Tolerance is justified in ``TOL`` below, not chosen to make anything pass.

CONVENTIONS ENCODED (authoritative source: docs/methodology/NOTATION_AND_CONVENTIONS.md)
----------------------------------------------------------------------------------------
* SI units; angles in radians internally.
* Frames: ``I`` = flat-Earth NED inertial (x North, y East, **z Down**);
  ``B`` = body (x forward, y right, z down).  Both right-handed.
* Transformations are **passive**, read "to <- from":  ``v_B = T_b_from_i @ v_I``.
* Euler 3-2-1:  ``T_b_from_i(phi, theta, psi) = R_x(phi) R_y(theta) R_z(psi)`` with

      R_x(a) = [[1,0,0], [0, cos a, sin a], [0, -sin a, cos a]]
      R_y(a) = [[cos a, 0, -sin a], [0,1,0], [sin a, 0, cos a]]
      R_z(a) = [[cos a, sin a, 0], [-sin a, cos a, 0], [0,0,1]]

* Quaternion: **Hamilton product, scalar-first**, ``quat = (q0, q1, q2, q3)``,
  meaning ``quat_b_from_i``.
* Quaternion composition order is the **reverse** of matrix order (audit finding F-4):
  ``T(qa (x) qb) = T(qb) T(qa)``.
* ``T_b_from_i(quat)`` is defined for **non-unit** quaternions by dividing by
  ``quat . quat`` (audit finding F-3, assumption ``A-NUM-05``).

STATUS
------
``radius.frames`` and ``radius.math.quaternion`` exist, so the attitude anchors execute
against real code.  The **wind frame does not exist yet**: the V-FRM-05 anchors are
established and executing as properties of their own hand-derived literals, while the
four tests that apply them to ``dcm_b_from_w`` skip until it is written.  Those are the
only skips in this file, and their reason names the missing function explicitly.

An anchor being mathematically established is not the same as an executable test running
against an implementation.  This file keeps the two visibly separate rather than letting
a skip read as coverage.

API names here are this file's *proposal*, consistent with the naming rules in
NOTATION_AND_CONVENTIONS.md section 8.  If an implementation chooses different names,
update the imports — but **the numerical anchors must not change**.  A failing anchor
means the implementation is wrong, or the convention has been deliberately changed via
an ADR and this file is stale.  It never means the anchor should be adjusted to fit.

DEMONSTRATED TO HAVE TEETH
--------------------------
A suite that only skips proves nothing, and a suite that passes under a wrong
convention is worse than none.  Before this file was committed it was run against
throwaway implementations carrying deliberate, individually injected convention errors
(mutation testing, 2026-09-09; harness kept out of the repository as a scratch
artifact).  The correct implementation passes every test, and each of the following was
caught —

    active/T_i_from_b instead of passive T_b_from_i ....... 16 failures
    scalar-LAST quaternion ordering ....................... 7 failures
    sign error in R_y (the -sin(theta) entry) ............. 3 failures
    3-2-1 Euler factors composed in reverse order ......... 2 failures
    reversed quaternion product order (audit F-4) ......... 1 failure
    missing /(quat.quat) for non-unit quaternions (F-3) ... 1 failure

The last two are caught by exactly one test each, which is the intended design: they
are the dedicated anchors for those findings.  If either of those tests is ever
weakened, the corresponding audit finding loses its only guard.

HOW TO RUN — and one command that must NOT be used
--------------------------------------------------
Standard library only; pytest is not a project dependency and is not installed.

From the repository root::

    python -m unittest discover -s tests -t tests

**Do not use ``python tests/test_frames.py``.**  Running the file as a script puts
``tests/`` on ``sys.path`` rather than the repository root, so ``import radius`` fails,
every test skips, and unittest prints ``OK (skipped=N)``.  That reads as success while
having verified nothing — the precise failure mode this file exists to prevent.  The
``__main__`` block below is retained only for use with the repository root already on
``PYTHONPATH``.

(``discover -s tests -t .`` is unavailable: Python 3.11+ requires the start directory to
be importable, which would mean adding ``tests/__init__.py``.  That has not been done,
because the command above works without it.)
"""

import math
import unittest

# --------------------------------------------------------------------------------------
# Implementation under test.  Absent by design during Phase 2A.
# --------------------------------------------------------------------------------------
try:  # pragma: no cover - exercised only once radius/ exists
    from radius.frames import (
        dcm_b_from_i_euler,   # (phi_rad, theta_rad, psi_rad) -> 3x3, rows indexable
        dcm_b_from_i_quat,    # (quat scalar-first, possibly non-unit) -> 3x3
        quat_b_from_i_euler,  # (phi_rad, theta_rad, psi_rad) -> 4, scalar-first
    )
    from radius.math.quaternion import quat_multiply  # Hamilton, scalar-first

    _IMPL_AVAILABLE = True
    _SKIP_REASON = ""
except ImportError as _exc:  # expected during Phase 2A
    _IMPL_AVAILABLE = False
    _SKIP_REASON = (
        "radius.frames / radius.math.quaternion not implemented yet (Phase 2A: anchors "
        f"are written before the implementation). Import error: {_exc}"
    )


# --------------------------------------------------------------------------------------
# Tolerance — justified, not tuned.
# --------------------------------------------------------------------------------------
# Every anchor below is O(1) in magnitude and reachable in O(10) floating-point
# operations, so the honest error budget is a few ULP, ~1e-16.  The one unavoidable
# contribution is the trig argument itself: cos(pi/2) evaluates to 6.1e-17, not to zero,
# so a strict equality test would fail for a *correct* implementation.
#
# 1e-12 leaves four orders of magnitude of headroom above that noise floor, which keeps
# the tests from being brittle across platforms and libm versions.
#
# It is nowhere near loose enough to hide the errors these tests exist to catch: a
# transposed matrix, a reversed composition order, an active-instead-of-passive rotation
# or a flipped sign all produce discrepancies of order 0.1 to 2.0 — ten to twelve orders
# of magnitude above this threshold.  The tolerance therefore separates "floating-point
# noise" from "wrong convention" by a margin that leaves no ambiguity.
TOL = 1e-12

SQRT2_2 = math.sqrt(2.0) / 2.0   # 0.70710678118654752
SQRT2_4 = math.sqrt(2.0) / 4.0   # 0.35355339059327376
SQRT3_2 = math.sqrt(3.0) / 2.0   # 0.86602540378443865
SQRT3_4 = math.sqrt(3.0) / 4.0   # 0.43301270189221932
SQRT6_4 = math.sqrt(6.0) / 4.0   # 0.61237243569579452


# --------------------------------------------------------------------------------------
# Local helpers.  Deliberately dependency-free and independent of the code under test:
# a matrix-vector product written here cannot inherit a convention error from radius/.
# --------------------------------------------------------------------------------------
def _rows(matrix):
    """Return a 3x3 as a plain nested list, whatever container the implementation uses."""
    return [[float(matrix[i][j]) for j in range(3)] for i in range(3)]


def _matvec(matrix, vector):
    return [sum(float(matrix[i][k]) * vector[k] for k in range(3)) for i in range(3)]


def _transpose(matrix):
    return [[matrix[j][i] for j in range(3)] for i in range(3)]


def _max_abs_diff(a, b):
    return max(abs(a[i][j] - b[i][j]) for i in range(3) for j in range(3))


class _AnchorAssertions(unittest.TestCase):
    """Assertions that say *which convention error* a failure implies.

    A bare "matrices differ" failure sends the reader looking for an arithmetic slip.
    These messages name the specific misconvention whose signature the actual result
    matches, which is usually the whole diagnosis.
    """

    def assert_matrix(self, actual, expected, what):
        got = _rows(actual)
        if _max_abs_diff(got, expected) <= TOL:
            return

        diagnosis = ""
        if _max_abs_diff(_transpose(got), expected) <= TOL:
            diagnosis = (
                "\n  DIAGNOSIS: the result is the TRANSPOSE of the expected matrix. "
                "The implementation is producing T_i_from_b (or an active rotation) "
                "where the passive 'to <- from' convention requires T_b_from_i. "
                "See NOTATION_AND_CONVENTIONS.md section 4."
            )
        self.fail(
            f"{what}\n"
            f"  expected: {expected}\n"
            f"  actual:   {got}\n"
            f"  max |diff| = {_max_abs_diff(got, expected):.3e} (tol {TOL:.0e})"
            f"{diagnosis}"
        )

    def assert_vector(self, actual, expected, what):
        got = [float(x) for x in actual]
        worst = max(abs(g - e) for g, e in zip(got, expected))
        if worst <= TOL:
            return
        self.fail(
            f"{what}\n  expected: {expected}\n  actual:   {got}\n"
            f"  max |diff| = {worst:.3e} (tol {TOL:.0e})"
        )


# ======================================================================================
# V-FRM-08 — 90 degree yaw convention anchor
# ======================================================================================
@unittest.skipUnless(_IMPL_AVAILABLE, _SKIP_REASON)
class TestVFRM08YawConvention(_AnchorAssertions):
    """V-FRM-08: the single hand-computed anchor that pins the yaw convention.

    HAND DERIVATION (no implementation involved)
    --------------------------------------------
    With phi = theta = 0 and psi = 90 deg, the 3-2-1 composition collapses to
    T_b_from_i = R_z(pi/2).  Substituting cos(pi/2) = 0 and sin(pi/2) = 1 into the
    documented R_z:

        R_z(pi/2) = [[ 0, 1, 0],
                     [-1, 0, 0],
                     [ 0, 0, 1]]

    PHYSICAL CROSS-CHECK (an independent route to the same answer)
    --------------------------------------------------------------
    The rows of T_b_from_i are the body axes expressed in inertial components.  After a
    +90 deg yaw the nose points East, so x_B = (0,1,0) = row 0.  The right wing then
    points South, so y_B = (-1,0,0) = row 1.  Yaw does not tilt the vehicle, so
    z_B = (0,0,1) = row 2.  This agrees with the matrix above, derived two different
    ways.

    WHAT THIS CATCHES
    -----------------
    * Active/passive inversion, and T_i_from_b returned where T_b_from_i was asked for:
      both give the transpose, which sends x_I to +y_B instead of -y_B.
    * A sign error in R_z.
    * An ENU (z-up) frame substituted for NED.
    * A left-handed axis set.

    None of these is detectable by orthonormality or by a round trip: the transpose of a
    rotation is a perfectly good rotation, and round-trips through it are exact.
    """

    def setUp(self):
        self.T = dcm_b_from_i_euler(0.0, 0.0, math.pi / 2.0)

    def test_v_frm_08_x_inertial_maps_to_minus_y_body(self):
        # The anchor named in the audit: +x_I -> -y_B.
        self.assert_vector(
            _matvec(self.T, [1.0, 0.0, 0.0]),
            [0.0, -1.0, 0.0],
            "V-FRM-08: a North-pointing inertial unit vector must appear along -y_B "
            "after a +90 deg yaw. A result of (0,+1,0) means the transformation is "
            "being applied in the wrong direction.",
        )

    def test_v_frm_08_remaining_basis_vectors(self):
        # y_I (East) lies along the nose after a +90 deg yaw; z_I is untouched by yaw.
        self.assert_vector(
            _matvec(self.T, [0.0, 1.0, 0.0]), [1.0, 0.0, 0.0],
            "V-FRM-08: +y_I (East) must map to +x_B after a +90 deg yaw.",
        )
        self.assert_vector(
            _matvec(self.T, [0.0, 0.0, 1.0]), [0.0, 0.0, 1.0],
            "V-FRM-08: +z_I (Down) is invariant under yaw.",
        )

    def test_v_frm_08_asymmetric_vector(self):
        # Basis vectors alone cannot separate every sign error, because each exercises
        # one column.  (3,4,5) has three distinct non-zero components, so a swapped or
        # mis-signed entry anywhere in the matrix changes the answer.
        # By hand: row0.v = 4, row1.v = -3, row2.v = 5.
        self.assert_vector(
            _matvec(self.T, [3.0, 4.0, 5.0]), [4.0, -3.0, 5.0],
            "V-FRM-08: hand-computed transform of an asymmetric vector.",
        )

    def test_v_frm_08_full_matrix(self):
        self.assert_matrix(
            self.T,
            [[0.0, 1.0, 0.0],
             [-1.0, 0.0, 0.0],
             [0.0, 0.0, 1.0]],
            "V-FRM-08: T_b_from_i(0, 0, 90 deg) must equal the hand-derived R_z(pi/2).",
        )


# ======================================================================================
# V-ATT-01 — hand-computed attitude / DCM anchors
# ======================================================================================
@unittest.skipUnless(_IMPL_AVAILABLE, _SKIP_REASON)
class TestVATT01AttitudeAnchors(_AnchorAssertions):
    """V-ATT-01: hand-derived DCMs for attitudes of increasing structure.

    Each expected matrix below was obtained by substituting exact trigonometric values
    into the elementary matrices documented in NOTATION_AND_CONVENTIONS.md section 4 and
    multiplying by hand.  The quaternion anchors were obtained by writing out the
    Hamilton product term by term.

    Where both the Euler path and the quaternion path are checked, each is compared
    against the *same hand-derived literal* — never against the other.  Two
    implementation paths that share a convention error agree with each other perfectly.
    """

    # -- Case 1: zero attitude -----------------------------------------------------
    def test_v_att_01_case1_identity_attitude(self):
        """Weak on its own, but it is the case that fails loudly if angle arguments are
        transposed in the signature (phi/theta/psi order) *and* a non-zero default is
        ever introduced. Kept as the base of the ladder."""
        identity = [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]
        self.assert_matrix(
            dcm_b_from_i_euler(0.0, 0.0, 0.0), identity,
            "V-ATT-01 case 1: zero attitude must give the identity DCM.",
        )
        self.assert_vector(
            quat_b_from_i_euler(0.0, 0.0, 0.0), [1.0, 0.0, 0.0, 0.0],
            "V-ATT-01 case 1: zero attitude must give the identity quaternion "
            "(1,0,0,0) in scalar-first ordering. A result of (0,0,0,1) means the "
            "implementation is scalar-LAST, which is a different convention.",
        )
        self.assert_matrix(
            dcm_b_from_i_quat([1.0, 0.0, 0.0, 0.0]), identity,
            "V-ATT-01 case 1: identity quaternion must give the identity DCM.",
        )

    # -- Case 2: principal-axis rotations -------------------------------------------
    #
    # Hand derivation, substituting cos(pi/2)=0, sin(pi/2)=1:
    #   roll  90:  R_x(pi/2) = [[1,0,0],[0,0,1],[0,-1,0]]
    #   pitch 90:  R_y(pi/2) = [[0,0,-1],[0,1,0],[1,0,0]]
    #   yaw   90:  R_z(pi/2) = [[0,1,0],[-1,0,0],[0,0,1]]
    #
    # Quaternions, from q = (cos(angle/2), axis * sin(angle/2)) with angle = pi/2:
    #   roll  90:  (sqrt2/2, sqrt2/2, 0, 0)
    #   pitch 90:  (sqrt2/2, 0, sqrt2/2, 0)
    #   yaw   90:  (sqrt2/2, 0, 0, sqrt2/2)
    #
    # These three are what isolate a single mis-signed elementary matrix. R_y carries the
    # -sin in its [0][2] entry where R_x and R_z carry +sin in [1][2] and [0][1]; that
    # asymmetry is real and is the most commonly mis-transcribed of the three.

    PRINCIPAL_CASES = (
        ("roll 90 deg", (math.pi / 2.0, 0.0, 0.0),
         [[1.0, 0.0, 0.0], [0.0, 0.0, 1.0], [0.0, -1.0, 0.0]],
         [SQRT2_2, SQRT2_2, 0.0, 0.0]),
        ("pitch 90 deg", (0.0, math.pi / 2.0, 0.0),
         [[0.0, 0.0, -1.0], [0.0, 1.0, 0.0], [1.0, 0.0, 0.0]],
         [SQRT2_2, 0.0, SQRT2_2, 0.0]),
        ("yaw 90 deg", (0.0, 0.0, math.pi / 2.0),
         [[0.0, 1.0, 0.0], [-1.0, 0.0, 0.0], [0.0, 0.0, 1.0]],
         [SQRT2_2, 0.0, 0.0, SQRT2_2]),
    )

    def test_v_att_01_case2_principal_axis_euler(self):
        for name, angles, expected, _quat in self.PRINCIPAL_CASES:
            with self.subTest(case=name):
                self.assert_matrix(
                    dcm_b_from_i_euler(*angles), expected,
                    f"V-ATT-01 case 2 ({name}): hand-derived elementary DCM. "
                    "A failure on pitch alone points at the -sin(theta) entry of R_y.",
                )

    def test_v_att_01_case2_principal_axis_quaternion(self):
        for name, angles, expected, quat in self.PRINCIPAL_CASES:
            with self.subTest(case=name):
                # Both paths are checked against the SAME hand literal, so a shared
                # convention error cannot cancel out between them.
                self.assert_vector(
                    quat_b_from_i_euler(*angles), quat,
                    f"V-ATT-01 case 2 ({name}): hand-derived quaternion, scalar-first.",
                )
                self.assert_matrix(
                    dcm_b_from_i_quat(quat), expected,
                    f"V-ATT-01 case 2 ({name}): the hand-derived quaternion must "
                    "produce the hand-derived DCM.",
                )

    # -- Case 3: combined attitude, integer entries, pins composition ORDER ----------
    #
    # yaw 90 deg then pitch 90 deg (phi = 0):
    #   T = R_y(pi/2) R_z(pi/2)
    #     = [[0,0,-1],[0,1,0],[1,0,0]] @ [[0,1,0],[-1,0,0],[0,0,1]]
    #     = [[0,0,-1],[-1,0,0],[0,1,0]]      (multiplied out by hand)
    #
    # Physical cross-check: after a +90 deg yaw the nose is East and the right wing
    # South; pitching +90 deg about that (South-pointing) body y-axis lifts the nose to
    # Up and swings the belly-down axis round to East. So the body axes in inertial
    # components are x_B = Up = (0,0,-1), y_B = South = (-1,0,0), z_B = East = (0,1,0) —
    # exactly the rows above, reached without touching the matrices.
    COMBINED_ANGLES = (0.0, math.pi / 2.0, math.pi / 2.0)
    COMBINED_DCM = [[0.0, 0.0, -1.0], [-1.0, 0.0, 0.0], [0.0, 1.0, 0.0]]
    COMBINED_QUAT = [0.5, -0.5, 0.5, 0.5]

    def test_v_att_01_case3_combined_euler(self):
        self.assert_matrix(
            dcm_b_from_i_euler(*self.COMBINED_ANGLES), self.COMBINED_DCM,
            "V-ATT-01 case 3: hand-multiplied R_y(90) R_z(90). A failure here with "
            "case 2 passing means the 3-2-1 factors are being composed in the wrong "
            "order.",
        )

    def test_v_att_01_case3_combined_quaternion_composition_order(self):
        """This is the case that pins audit finding F-4.

        Quaternion composition is the REVERSE of matrix composition:
        T(qa (x) qb) = T(qb) T(qa).  To build T = R_y R_z we therefore need
        qa = q_yaw and qb = q_pitch, i.e. quat = q_yaw (x) q_pitch.

        Hand-computed Hamilton product, with H = sqrt(2)/2:
            q_yaw   = (H, 0, 0, H)
            q_pitch = (H, 0, H, 0)
            scalar  = H*H - (0,0,H).(0,H,0)          = 0.5 - 0    =  0.5
            vector  = H*(0,H,0) + H*(0,0,H) + (0,0,H) x (0,H,0)
                    = (0, 0.5, 0) + (0, 0, 0.5) + (-0.5, 0, 0)
                    = (-0.5, 0.5, 0.5)
            quat    = (0.5, -0.5, 0.5, 0.5)

        The reversed order gives (0.5, +0.5, 0.5, 0.5) — the x component flips sign —
        whose DCM is [[0,1,0],[0,0,1],[1,0,0]], a completely different attitude.  So
        this test discriminates the two orders rather than merely exercising one.
        """
        quat = quat_multiply([SQRT2_2, 0.0, 0.0, SQRT2_2],   # q_yaw
                             [SQRT2_2, 0.0, SQRT2_2, 0.0])   # q_pitch
        self.assert_vector(
            quat, self.COMBINED_QUAT,
            "V-ATT-01 case 3: hand-computed Hamilton product q_yaw (x) q_pitch. A "
            "result of (0.5, +0.5, 0.5, 0.5) means the product operands are being "
            "applied in the reversed (JPL-style) order.",
        )
        self.assert_matrix(
            dcm_b_from_i_quat(quat), self.COMBINED_DCM,
            "V-ATT-01 case 3: the composed quaternion must give the same hand-derived "
            "DCM as the Euler route.",
        )
        self.assert_vector(
            quat_b_from_i_euler(*self.COMBINED_ANGLES), self.COMBINED_QUAT,
            "V-ATT-01 case 3: Euler-to-quaternion must agree with the hand-computed "
            "Hamilton product.",
        )

    # -- Case 4: asymmetric combined attitude, exact surds --------------------------
    #
    # yaw 45 deg, pitch 30 deg, roll 0.  T = R_y(30) R_z(45), multiplied out by hand
    # from cos30 = sqrt3/2, sin30 = 1/2, cos45 = sin45 = sqrt2/2:
    #
    #   T = [[ sqrt6/4,  sqrt6/4, -1/2   ],
    #        [-sqrt2/2,  sqrt2/2,  0     ],
    #        [ sqrt2/4,  sqrt2/4,  sqrt3/2]]
    #
    # Every 90 deg case above has entries in {0, +-1}, which makes several distinct
    # misconventions produce matrices that are permutations of one another and can mask
    # each other.  This case has six distinct irrational magnitudes, is not symmetric
    # (T[0][2] = -0.5 while T[2][0] = +0.354), and therefore separates a transposed
    # result from a correct one on magnitude alone — not merely on sign.
    ASYMMETRIC_ANGLES = (0.0, math.radians(30.0), math.radians(45.0))
    ASYMMETRIC_DCM = [
        [SQRT6_4, SQRT6_4, -0.5],
        [-SQRT2_2, SQRT2_2, 0.0],
        [SQRT2_4, SQRT2_4, SQRT3_2],
    ]

    def test_v_att_01_case4_asymmetric_euler(self):
        self.assert_matrix(
            dcm_b_from_i_euler(*self.ASYMMETRIC_ANGLES), self.ASYMMETRIC_DCM,
            "V-ATT-01 case 4: hand-multiplied R_y(30) R_z(45). Distinct irrational "
            "entries make a transposition detectable by magnitude, not just by sign.",
        )

    def test_v_att_01_case4_asymmetric_quaternion(self):
        # Same literal, reached through the quaternion representation.
        self.assert_matrix(
            dcm_b_from_i_quat(quat_b_from_i_euler(*self.ASYMMETRIC_ANGLES)),
            self.ASYMMETRIC_DCM,
            "V-ATT-01 case 4: the quaternion route must reproduce the same "
            "hand-derived DCM as the Euler route.",
        )

    # -- Quaternion argument handling, anchored to case 2's literal ------------------
    #
    # Both sub-cases below are anchored to the hand-derived R_z(pi/2) literal, so
    # neither is a round trip or a self-consistency check.
    #
    # These OVERLAP with, but are not superseded by, the dedicated V-FRM-09 anchors
    # further down.  They are retained deliberately: this pair uses an axis-aligned
    # quaternion (yaw 90) where V-FRM-09 uses a non-axis-aligned one, so the two
    # exercise different numerical cases of the same property.  If either is ever
    # removed it should be this pair, not V-FRM-09 -- and only with the overlap
    # re-checked, since these are the only sub-cases covering exact negation (k = -1).

    YAW90_QUAT = [SQRT2_2, 0.0, 0.0, SQRT2_2]
    YAW90_DCM = [[0.0, 1.0, 0.0], [-1.0, 0.0, 0.0], [0.0, 0.0, 1.0]]

    def test_v_att_01_non_unit_quaternion(self):
        """A-NUM-05. RK stages necessarily evaluate the derivative at non-unit
        quaternions.  Because T(k*q) = k^2 T(q), an implementation that omits the
        division by quat.quat silently scales every force by ||quat||^2 inside stages
        2-4 of every step.  Scaling by 2 here makes that a factor of 4."""
        self.assert_matrix(
            dcm_b_from_i_quat([2.0 * x for x in self.YAW90_QUAT]), self.YAW90_DCM,
            "V-ATT-01 (A-NUM-05): a quaternion of norm 2 must give the same rotation "
            "as the unit quaternion. A result scaled by 4 means the division by "
            "quat.quat is missing.",
        )

    def test_v_att_01_negated_quaternion_double_cover(self):
        """quat and -quat are the same attitude; the DCM formula is quadratic in quat,
        so this must hold exactly rather than approximately."""
        self.assert_matrix(
            dcm_b_from_i_quat([-x for x in self.YAW90_QUAT]), self.YAW90_DCM,
            "V-ATT-01: negating a quaternion must not change the attitude it "
            "represents (double cover).",
        )


# ======================================================================================
# V-FRM-09 — non-unit quaternion invariance / the q.q denominator
# ======================================================================================
#
# TRACEABILITY
#     audit finding F-3  ->  assumption A-NUM-05  ->  V-FRM-09  ->  dcm_b_from_i_quat
#
# See PRE_IMPLEMENTATION_MATHEMATICAL_AUDIT.md section 2.4 and docs/assumptions.md.
#
@unittest.skipUnless(_IMPL_AVAILABLE, _SKIP_REASON)
class TestVFRM09NonUnitQuaternion(_AnchorAssertions):
    """V-FRM-09: T(quat) must equal T(k*quat) for every non-zero scalar k.

    WHY THIS PROPERTY IS LOAD-BEARING
    ---------------------------------
    An RK stage evaluates the derivative at ``x_n + (h/2) k_1``, whose quaternion block
    is **necessarily** not of unit norm.  Because ``T(k*quat) = k^2 T(quat)``, an
    implementation that assumes unit input silently scales every aerodynamic and
    propulsive force by ``||quat||^2`` in stages 2 through 4 of every single step.  The
    trajectory that results is smooth, plausible, and wrong.

    The specification therefore defines the map by *division* by ``quat . quat`` -- not
    by normalising the input, which would change the function being integrated and
    introduce a branch (NOTATION_AND_CONVENTIONS.md section 4, A-NUM-05).

    WHY INVARIANCE ALONE WOULD BE AN INADEQUATE TEST
    ------------------------------------------------
    Asserting only ``T(quat) == T(2*quat)`` is satisfied by an implementation that
    normalises its input internally -- exactly the behaviour the specification forbids.
    It is also satisfied by an implementation that returns a constant.  This test
    therefore checks invariance **and** agreement with an independently derived DCM
    simultaneously; neither half is sufficient alone.

    HAND DERIVATION (no implementation involved)
    --------------------------------------------
    Take the deliberately non-unit, non-axis-aligned quaternion

        quat = (1, 2, 3, 4),   quat . quat = 1 + 4 + 9 + 16 = 30

    With q0 = 1 and qv = (2, 3, 4), so qv . qv = 29:

        (q0^2 - qv.qv) I = -28 I
        2 qv qv^T        = [[8,12,16], [12,18,24], [16,24,32]]
        -2 q0 [qv x]     = [[0,8,-6], [-8,0,4], [6,-4,0]]

    Summing and dividing by 30:

        T = [[-20, 20, 10], [4, -10, 28], [22, 20, 4]] / 30
          = [[-2/3,   2/3,  1/3 ],
             [ 2/15, -1/3,  14/15],
             [11/15,  2/3,  2/15]]

    This anchor is unusually strong: the entries are *exactly rational*, and the matrix
    is orthonormal with determinant +1 in exact rational arithmetic (verified in
    Fractions during derivation, not in floating point).  It is also asymmetric --
    T[0][1] = 2/3 while T[1][0] = 2/15 -- so a transposed result differs in magnitude,
    not merely in sign.

    NON-VACUITY
    -----------
    Without the ``/(quat . quat)`` denominator the k=1 result is 30x too large:
    entry [0][0] would be -20 rather than -2/3.  There is no tolerance at which that
    passes.  Confirmed by mutation testing: deleting the denominator fails four of the
    four scale factors here, by margins from 6.1 to 1.5e3.

    WHAT THIS ANCHOR CANNOT ESTABLISH
    ---------------------------------
    A-NUM-05 asks for two things: that the map be scale-invariant, and that it be
    achieved by *division* rather than by normalising the input.  This test establishes
    the first.  It cannot establish the second, and neither can any other output-level
    test: an implementation that unconditionally normalises a local copy of ``quat``
    returns the same matrix -- measured, over 2000 random non-unit quaternions, as
    agreeing to 5.6e-16.  The two are the same mathematical map.

    That is not a gap in the test; it is a fact about the specification.  The part of
    A-NUM-05 that a test can reach is the observable behaviour, which is pinned here.
    The part it cannot reach is branch-freedom, which matters for the determinism
    guarantee in docs/PROVENANCE.md section 5 and is a property of the *source*,
    verifiable by reading it rather than by running it.  Recording the distinction so
    that passing this test is not mistaken for having verified all of A-NUM-05.
    """

    # Deliberately non-unit (norm sqrt(30)) and non-axis-aligned (all three vector
    # components non-zero).  The identity quaternion would be useless here: it is unit,
    # axis-aligned, and its DCM is invariant under errors this test must catch.
    QUAT = [1.0, 2.0, 3.0, 4.0]

    # Hand-derived above.  Written as exact rational expressions rather than decimal
    # approximations so the derivation stays legible in the source.
    EXPECTED_DCM = [
        [-2.0 / 3.0, 2.0 / 3.0, 1.0 / 3.0],
        [2.0 / 15.0, -1.0 / 3.0, 14.0 / 15.0],
        [11.0 / 15.0, 2.0 / 3.0, 2.0 / 15.0],
    ]

    # k = 1 establishes the literal; the rest establish invariance.  -7.25 is included
    # because a negative, non-dyadic scale factor exercises sign handling and the
    # double cover at the same time, and 0.5/2.0 bracket unity from both sides.
    SCALE_FACTORS = (1.0, 2.0, 0.5, -7.25)

    def test_v_frm_09_anchor_quaternion_is_fit_for_purpose(self):
        """Guard on the anchor itself, not on the implementation.

        If a later edit "tidies" QUAT into a unit or axis-aligned quaternion, this test
        loses its power silently. This makes that edit fail loudly instead.
        """
        norm_sq = sum(x * x for x in self.QUAT)
        self.assertEqual(
            norm_sq, 30.0,
            "V-FRM-09 requires a NON-UNIT anchor quaternion; quat.quat must be 30.",
        )
        self.assertTrue(
            all(component != 0.0 for component in self.QUAT[1:]),
            "V-FRM-09 requires a NON-AXIS-ALIGNED anchor: all three vector components "
            "must be non-zero.",
        )

    def test_v_frm_09_scaled_quaternions_give_the_hand_derived_dcm(self):
        for k in self.SCALE_FACTORS:
            with self.subTest(scale=k):
                scaled = [k * component for component in self.QUAT]
                self.assert_matrix(
                    dcm_b_from_i_quat(scaled), self.EXPECTED_DCM,
                    f"V-FRM-09 (k = {k}): T(k * quat) must equal the hand-derived DCM "
                    "for quat = (1,2,3,4). A result larger by a factor of "
                    f"{k * k * 30.0:g} means the division by quat.quat is missing "
                    "(audit F-3, A-NUM-05).",
                )


# ======================================================================================
# V-FRM-10 — quaternion composition order
# ======================================================================================
#
# TRACEABILITY
#     audit finding F-4  ->  V-FRM-10  ->  quat_multiply / composition order
#
# See PRE_IMPLEMENTATION_MATHEMATICAL_AUDIT.md section 2.5.
#
@unittest.skipUnless(_IMPL_AVAILABLE, _SKIP_REASON)
class TestVFRM10CompositionOrder(_AnchorAssertions):
    """V-FRM-10: T(qa (x) qb) = T(qb) T(qa) -- the orders are REVERSED.

    Quaternion multiplication is non-commutative; this test exists specifically to
    prevent the composition-order error identified as F-4 during the pre-implementation
    audit.  Matrices compose by adjacency, quaternions in this convention do not, and an
    implementer would reasonably assume the two match.

    WHY THE IDENTITY ALONE IS NOT ENOUGH
    ------------------------------------
    Checking only ``T(qa (x) qb) == T(qb) @ T(qa)`` compares two results produced by the
    same implementation.  If ``quat_multiply`` and ``dcm_b_from_i_quat`` shared a
    convention error the identity could still hold.  Every quantity below is therefore
    pinned to an independently hand-derived literal, and the identity is checked *as a
    consequence* of those literals rather than as the primary evidence.

    ROTATION PAIR
    -------------
    Roll 90 deg and pitch 90 deg: distinct axes, and genuinely non-commuting.  (Two
    rotations about the same axis commute, which would make this test vacuous.)  This is
    a different numerical case from V-ATT-01 case 3, which uses yaw+pitch, so the two
    are not duplicates.

    HAND DERIVATION (no implementation involved), with h = sqrt(2)/2, h*h = 1/2:

        qa = q_roll(90)  = (h, h, 0, 0)
        qb = q_pitch(90) = (h, 0, h, 0)

        qa (x) qb:
            scalar = h*h - (h,0,0).(0,h,0)               = 1/2 - 0   = 1/2
            vector = h*(0,h,0) + h*(h,0,0) + (h,0,0)x(0,h,0)
                   = (0,1/2,0) + (1/2,0,0) + (0,0,1/2)   = (1/2, 1/2, 1/2)
            => qa (x) qb = (1/2, 1/2, 1/2, 1/2)

        qb (x) qa:
            scalar = 1/2 - 0                                          = 1/2
            vector = h*(h,0,0) + h*(0,h,0) + (0,h,0)x(h,0,0)
                   = (1/2,0,0) + (0,1/2,0) + (0,0,-1/2) = (1/2, 1/2, -1/2)
            => qb (x) qa = (1/2, 1/2, 1/2, -1/2)

    The two differ in the last component -- the product is non-commutative, as required
    for this test to discriminate anything.

    Substituting each into the DCM formula by hand:

        T(qa (x) qb) = [[0, 1, 0], [0, 0, 1], [1, 0, 0]]
        T(qb (x) qa) = [[0, 0,-1], [1, 0, 0], [0,-1, 0]]

    Independently, from the elementary matrices of NOTATION section 4:

        R_y(90) @ R_x(90) = [[0, 1, 0], [0, 0, 1], [1, 0, 0]]   == T(qa (x) qb)
        R_x(90) @ R_y(90) = [[0, 0,-1], [1, 0, 0], [0,-1, 0]]   == T(qb (x) qa)

    which is the identity T(qa (x) qb) = T(qb) @ T(qa) reached by a second route.
    """

    QUAT_A_ROLL90 = [SQRT2_2, SQRT2_2, 0.0, 0.0]
    QUAT_B_PITCH90 = [SQRT2_2, 0.0, SQRT2_2, 0.0]

    QUAT_A_TIMES_B = [0.5, 0.5, 0.5, 0.5]
    QUAT_B_TIMES_A = [0.5, 0.5, 0.5, -0.5]

    DCM_A_TIMES_B = [[0.0, 1.0, 0.0], [0.0, 0.0, 1.0], [1.0, 0.0, 0.0]]
    DCM_B_TIMES_A = [[0.0, 0.0, -1.0], [1.0, 0.0, 0.0], [0.0, -1.0, 0.0]]

    def test_v_frm_10_hamilton_product_both_orders(self):
        """Both orders pinned to literals -- which is what establishes that the product
        is non-commutative here, rather than merely asserting that it is."""
        self.assert_vector(
            quat_multiply(self.QUAT_A_ROLL90, self.QUAT_B_PITCH90),
            self.QUAT_A_TIMES_B,
            "V-FRM-10: hand-computed Hamilton product qa (x) qb.",
        )
        self.assert_vector(
            quat_multiply(self.QUAT_B_PITCH90, self.QUAT_A_ROLL90),
            self.QUAT_B_TIMES_A,
            "V-FRM-10: hand-computed Hamilton product qb (x) qa. If this equals the "
            "qa (x) qb value, the implementation has made the product commutative and "
            "the composition-order guarantee is void.",
        )

    def test_v_frm_10_composition_identity_against_literals(self):
        """T(qa (x) qb) = T(qb) T(qa), with BOTH sides anchored independently."""
        composed = quat_multiply(self.QUAT_A_ROLL90, self.QUAT_B_PITCH90)
        self.assert_matrix(
            dcm_b_from_i_quat(composed), self.DCM_A_TIMES_B,
            "V-FRM-10 (left side): the DCM of the composed quaternion.",
        )
        # Right side of the identity, built by multiplying the two single-axis DCMs in
        # the REVERSED order relative to the quaternion product. Anchored to the same
        # literal, so agreement is not evidence that two buggy paths concur.
        dcm_b = _rows(dcm_b_from_i_quat(self.QUAT_B_PITCH90))
        dcm_a = _rows(dcm_b_from_i_quat(self.QUAT_A_ROLL90))
        product = [[sum(dcm_b[i][k] * dcm_a[k][j] for k in range(3)) for j in range(3)]
                   for i in range(3)]
        self.assert_matrix(
            product, self.DCM_A_TIMES_B,
            "V-FRM-10 (right side): T(qb) @ T(qa) must equal the same hand-derived DCM. "
            "If T(qa) @ T(qb) were used instead the result would be the OTHER "
            "hand-derived matrix, DCM_B_TIMES_A.",
        )

    def test_v_frm_10_reversed_order_gives_a_different_anchored_result(self):
        """The wrong order does not merely differ -- it lands on a second, separately
        hand-derived matrix. Pinning the wrong answer too is what makes this test
        diagnostic rather than just a mismatch report."""
        reversed_product = quat_multiply(self.QUAT_B_PITCH90, self.QUAT_A_ROLL90)
        self.assert_matrix(
            dcm_b_from_i_quat(reversed_product), self.DCM_B_TIMES_A,
            "V-FRM-10: the reversed product must give the hand-derived DCM for "
            "qb (x) qa.",
        )

    def test_v_frm_10_orders_are_measurably_different(self):
        """Guards against a commutative implementation making the whole class vacuous.

        Asserted numerically against a stated threshold rather than with a qualitative
        condition: the two hand-derived matrices differ by exactly 1.0 in several
        entries, so anything below that is a real regression.
        """
        forward = _rows(dcm_b_from_i_quat(
            quat_multiply(self.QUAT_A_ROLL90, self.QUAT_B_PITCH90)))
        backward = _rows(dcm_b_from_i_quat(
            quat_multiply(self.QUAT_B_PITCH90, self.QUAT_A_ROLL90)))
        separation = _max_abs_diff(forward, backward)
        self.assertGreaterEqual(
            separation, 1.0,
            "V-FRM-10: T(qa (x) qb) and T(qb (x) qa) must be measurably different "
            f"(hand-derived separation is exactly 1.0); got {separation:.3e}. A "
            "separation near zero means quaternion multiplication has become "
            "commutative, which would make every composition-order test vacuous.",
        )


# ======================================================================================
# V-FRM-05 — wind-frame transformation convention
# ======================================================================================
#
# TRACEABILITY
#     audit finding F-2  ->  V-FRM-05  ->  T_BW (wind frame -> body frame)
#
# See PRE_IMPLEMENTATION_MATHEMATICAL_AUDIT.md section 9.1 and RS-001 section 2.3.
#
# THIS VERIFIES A COORDINATE TRANSFORMATION CONVENTION.  It is not an aerodynamic test
# and it validates no aerodynamic model: no coefficient, force or moment appears here,
# and the Q8 gate (no traceable coefficient source) is untouched by it.
#
# ---------------------------------------------------------------------------------
# INDEPENDENT RE-DERIVATION (the audit's corrected result was re-checked, not assumed)
# ---------------------------------------------------------------------------------
# RS-007 section 2 defines, from v_rel resolved in body axes as (u, v, w):
#
#       alpha = arctan2(w, u)          beta = arcsin(v / V)
#
# Inverting those two definitions gives the air-relative velocity in body axes:
#
#       v_B = V (cos a cos b,  sin b,  sin a cos b)
#
# In the wind frame the same physical vector is by definition purely along x_W, so
# v_W = (V, 0, 0).  Since v_B = T_BW v_W = V * (first column of T_BW), the definitions
# of alpha and beta FORCE, with no reference to any matrix composition:
#
#       first column of T_BW = (cos a cos b,  sin b,  sin a cos b)         (*)
#
# That is the independent constraint.  Composing the documented passive elementary
# matrices of NOTATION section 4:
#
#   R_z(-b) = [[ cos b, -sin b, 0], [ sin b,  cos b, 0], [ 0, 0, 1]]
#   R_y(a)  = [[ cos a, 0, -sin a], [ 0, 1, 0],          [ sin a, 0, cos a]]
#
#   R_y(a) R_z(-b) = [[ cos a cos b,  -cos a sin b,  -sin a],
#                     [ sin b,         cos b,         0    ],
#                     [ sin a cos b,  -sin a sin b,   cos a]]
#
# whose first column is exactly (*).  The superseded form R_y(-a) R_z(b) gives first
# column (cos a cos b, -sin b, -sin a cos b) -- both angles negated -- and therefore
# contradicts the definitions.  The audit's correction is confirmed by a route that
# does not use the audit's own reasoning.
#
_A_ZERO = 0.0
_B_30 = math.radians(30.0)
_A_30 = math.radians(30.0)
_B_60 = math.radians(60.0)


class _WindFrameAnchors:
    """The hand-derived V-FRM-05 literals, in a plain container.

    Deliberately NOT a TestCase. Both test classes below read their expected values from
    here, so the anchor and the implementation check are pinned to the same numbers with
    no possibility of drift -- and without the implementation class inheriting (and
    therefore re-collecting, then skipping) the anchor class's test methods.
    """

    CASE_A_DCM = [[SQRT3_2, -0.5, 0.0],
                  [0.5, SQRT3_2, 0.0],
                  [0.0, 0.0, 1.0]]
    # The superseded F-2 convention at alpha = 0, i.e. R_y(0) R_z(+beta).
    CASE_A_DCM_WRONG_SIGN = [[SQRT3_2, 0.5, 0.0],
                             [-0.5, SQRT3_2, 0.0],
                             [0.0, 0.0, 1.0]]
    CASE_A_V_WIND = [100.0, 0.0, 0.0]
    CASE_A_V_BODY = [50.0 * math.sqrt(3.0), 50.0, 0.0]

    CASE_B_DCM = [[SQRT3_4, -0.75, -0.5],
                  [SQRT3_2, 0.5, 0.0],
                  [0.25, -SQRT3_4, SQRT3_2]]
    # R_y(-alpha) R_z(+beta) -- the exact form RS-001 carried before the audit.
    CASE_B_DCM_SUPERSEDED = [[SQRT3_4, 0.75, 0.5],
                             [-SQRT3_2, 0.5, 0.0],
                             [-0.25, -SQRT3_4, SQRT3_2]]
    # R_z(-beta) R_y(alpha) -- correct factors, reversed composition order.
    CASE_B_DCM_REVERSED_ORDER = [[SQRT3_4, -SQRT3_2, -0.25],
                                 [0.75, 0.5, -SQRT3_4],
                                 [0.5, 0.0, SQRT3_2]]
    CASE_B_V_WIND = [100.0, 0.0, 0.0]
    CASE_B_V_BODY = [25.0 * math.sqrt(3.0), 50.0 * math.sqrt(3.0), 25.0]
    # A wind-frame vector with three distinct non-zero components, so that every one of
    # the nine matrix entries contributes to the result.
    CASE_B_V_WIND_GENERAL = [1.0, 2.0, 3.0]
    CASE_B_V_BODY_GENERAL = [math.sqrt(3.0) / 4.0 - 3.0,
                             math.sqrt(3.0) / 2.0 + 1.0,
                             0.25 + math.sqrt(3.0)]


class TestVFRM05WindFrameAnchor(_AnchorAssertions, _WindFrameAnchors):
    """V-FRM-05: the hand-derived wind-frame anchors, and what they discriminate.

    This class runs **now**, with no implementation, because everything it asserts is a
    property of the hand-derived literals themselves or of the definitions in (*) above.
    It establishes the anchor mathematically and executably; the separate class below
    applies it to an implementation once one exists.

    CASE A -- alpha = 0, beta = +30 deg.  Sideslip sign discriminator.
        T_BW = R_y(0) R_z(-30 deg) = [[sqrt3/2, -1/2, 0],
                                      [1/2,   sqrt3/2, 0],
                                      [0,       0,     1]]
        A positive sideslip must put a POSITIVE component on y_B: with V = 100,
        v_W = (100, 0, 0) maps to v_B = (50 sqrt3, 50, 0).  Reverting the F-2 sign
        gives v_B = (50 sqrt3, -50, 0) -- the aircraft sideslipping the wrong way.

    CASE B -- alpha = 30 deg, beta = 60 deg.  Coupled, asymmetric, nine distinct
    entries, no vanishing sine or cosine:
        T_BW = [[sqrt3/4, -3/4,     -1/2   ],
                [sqrt3/2,  1/2,      0     ],
                [1/4,     -sqrt3/4,  sqrt3/2]]

    WHY CASE B IS NOT OPTIONAL
    --------------------------
    At alpha = 0 the two composition orders **coincide**: R_y(0) R_z(-b) equals
    R_z(-b) R_y(0), because R_y(0) is the identity.  Case A therefore cannot detect a
    reversed composition order at all, and a suite containing only Case A would look
    thorough while being blind to one of the three errors this anchor exists to catch.
    That is asserted explicitly below rather than left as a remark.
    """

    def test_v_frm_05_first_column_matches_the_alpha_beta_definition(self):
        """The core of F-2, by the independent route (*).

        The anchor matrices were derived from the elementary-matrix composition.  Their
        first columns are checked here against ``(cos a cos b, sin b, sin a cos b)``,
        which comes from inverting the *definitions* of alpha and beta and never touches
        a composition.  Two independent derivations agreeing is the evidence; either one
        alone would not be.
        """
        for label, alpha, beta, dcm in (
            ("case A", _A_ZERO, _B_30, self.CASE_A_DCM),
            ("case B", _A_30, _B_60, self.CASE_B_DCM),
        ):
            with self.subTest(case=label):
                required = [math.cos(alpha) * math.cos(beta),
                            math.sin(beta),
                            math.sin(alpha) * math.cos(beta)]
                first_column = [dcm[0][0], dcm[1][0], dcm[2][0]]
                self.assert_vector(
                    first_column, required,
                    f"V-FRM-05 ({label}): the first column of T_BW is forced by the "
                    "definitions of alpha and beta to be (cos a cos b, sin b, "
                    "sin a cos b). If this fails, the composition and the angle "
                    "definitions disagree -- which is exactly defect F-2.",
                )

    def test_v_frm_05_superseded_convention_contradicts_the_definition(self):
        """The pre-audit form must FAIL the constraint (*), or the anchor proves nothing.

        Guards against the anchor being vacuous: if the superseded convention also
        satisfied the definition, this test would not distinguish the two and F-2 would
        not have been a defect.
        """
        required_y = math.sin(_B_60)  # +sin(beta)
        superseded_y = self.CASE_B_DCM_SUPERSEDED[1][0]
        self.assertAlmostEqual(
            superseded_y, -required_y, places=12,
            msg="V-FRM-05: the superseded R_y(-a)R_z(b) form must yield -sin(beta) in "
                "the first column, i.e. the opposite sideslip sense.",
        )
        self.assertGreater(
            abs(superseded_y - required_y), 1.7,
            "V-FRM-05: the superseded form must differ from the definition by a large "
            "margin (hand-derived separation is 2 sin 60 deg = sqrt3 ~ 1.732).",
        )

    def test_v_frm_05_case_a_discriminates_the_sideslip_sign(self):
        """Positive beta must put a POSITIVE component on y_B.

        Threshold note: the hand-derived separation is exactly 1.0, but sin(30 deg)
        evaluates to 0.49999999999999994, so the computed separation is 1 ULP below 1.0.
        The threshold is set just under the exact value for that reason and for no
        other; it is nowhere near the ~1e-16 noise floor.
        """
        separation = _max_abs_diff(self.CASE_A_DCM, self.CASE_A_DCM_WRONG_SIGN)
        self.assertGreater(
            separation, 0.99,
            "V-FRM-05 case A: the corrected and reverted sideslip signs must be "
            f"measurably different (hand-derived separation 1.0); got {separation:.3e}.",
        )
        # And the physically meaningful consequence, not just a matrix difference.
        self.assert_vector(
            _matvec(self.CASE_A_DCM, self.CASE_A_V_WIND), self.CASE_A_V_BODY,
            "V-FRM-05 case A: v_W = (100,0,0) at beta = +30 deg must give "
            "v_B = (50 sqrt3, +50, 0).",
        )
        wrong = _matvec(self.CASE_A_DCM_WRONG_SIGN, self.CASE_A_V_WIND)
        self.assertLess(
            wrong[1], -49.0,
            "V-FRM-05 case A: under the reverted sign the same vector must acquire a "
            "NEGATIVE y_B component (-50), i.e. sideslip to the wrong side. If this "
            "does not hold the two conventions are not being distinguished.",
        )

    def test_v_frm_05_case_b_discriminates_composition_order(self):
        """R_y(a) R_z(-b) vs R_z(-b) R_y(a), with both pinned to literals.

        Both orders are separately hand-derived, so this is not a comparison of two
        outputs of one implementation: the wrong answer is anchored too.
        """
        separation = _max_abs_diff(self.CASE_B_DCM, self.CASE_B_DCM_REVERSED_ORDER)
        self.assertGreater(
            separation, 0.4,
            "V-FRM-05 case B: the two composition orders must be measurably different "
            f"(hand-derived separation sqrt3/4 ~ 0.433); got {separation:.3e}.",
        )

    def test_v_frm_05_case_b_discriminates_active_passive_inversion(self):
        """The transpose is also a valid rotation with det +1, so orthonormality and
        determinant cannot tell the intended convention from its inverse. Only a pinned
        asymmetric matrix can."""
        separation = _max_abs_diff(self.CASE_B_DCM, _transpose(self.CASE_B_DCM))
        self.assertGreater(
            separation, 1.5,
            "V-FRM-05 case B: T_BW must be measurably different from its transpose "
            f"(hand-derived separation ~1.616); got {separation:.3e}. A small value "
            "would mean the anchor cannot detect an active/passive inversion.",
        )

    def test_v_frm_05_alpha_zero_cannot_discriminate_composition_order(self):
        """Why case B exists. At alpha = 0 the two orders coincide exactly, so case A is
        blind to a reversed composition. Asserting this keeps anyone from later deleting
        case B as redundant."""
        reversed_at_alpha_zero = [[SQRT3_2, -0.5, 0.0],
                                  [0.5, SQRT3_2, 0.0],
                                  [0.0, 0.0, 1.0]]  # R_z(-30) R_y(0), by hand
        self.assertLess(
            _max_abs_diff(self.CASE_A_DCM, reversed_at_alpha_zero), TOL,
            "V-FRM-05: at alpha = 0 the composition orders are identical. If this ever "
            "fails the reasoning for requiring case B has changed and should be "
            "re-examined.",
        )

    def test_v_frm_05_anchors_are_orthonormal_with_unit_determinant(self):
        """A sanity check on the LITERALS -- catches a transcription slip in this file.

        Explicitly NOT evidence of convention correctness: the transpose, the superseded
        form and the reversed order are all orthonormal with determinant +1 too. That is
        precisely why the discriminating tests above exist.
        """
        for label, dcm in (("case A", self.CASE_A_DCM), ("case B", self.CASE_B_DCM)):
            with self.subTest(case=label):
                product = [[sum(dcm[i][k] * dcm[j][k] for k in range(3))
                            for j in range(3)] for i in range(3)]
                self.assert_matrix(
                    product, [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]],
                    f"V-FRM-05 ({label}): the hand-transcribed literal must be "
                    "orthonormal. A failure here is a typo in this test file, not a "
                    "defect in the implementation.",
                )
                det = (dcm[0][0] * (dcm[1][1] * dcm[2][2] - dcm[1][2] * dcm[2][1])
                       - dcm[0][1] * (dcm[1][0] * dcm[2][2] - dcm[1][2] * dcm[2][0])
                       + dcm[0][2] * (dcm[1][0] * dcm[2][1] - dcm[1][1] * dcm[2][0]))
                self.assertAlmostEqual(
                    det, 1.0, places=12,
                    msg=f"V-FRM-05 ({label}): literal must have determinant +1.",
                )


# --------------------------------------------------------------------------------------
# V-FRM-05 applied to an implementation.
#
# PROPOSED INTERFACE, not yet implemented (RS-001 section 2.3; naming per
# NOTATION_AND_CONVENTIONS.md section 8, "to <- from"):
#
#     radius.frames.dcm_b_from_w(alpha_rad, beta_rad) -> 3x3
#
# It has its own import guard so that its absence cannot skip the rest of this file --
# a single shared guard would have silently disabled all 19 passing tests the moment a
# not-yet-written name was added to it.
# --------------------------------------------------------------------------------------
try:  # pragma: no cover - exercised only once the wind frame is implemented
    from radius.frames import dcm_b_from_w

    _WIND_IMPL_AVAILABLE = True
    _WIND_SKIP_REASON = ""
except ImportError as _wind_exc:
    _WIND_IMPL_AVAILABLE = False
    _WIND_SKIP_REASON = (
        "radius.frames.dcm_b_from_w is not implemented yet. The V-FRM-05 anchors above "
        f"are established and executing; only their application to code waits. ({_wind_exc})"
    )


@unittest.skipUnless(_WIND_IMPL_AVAILABLE, _WIND_SKIP_REASON)
class TestVFRM05WindFrameImplementation(_AnchorAssertions, _WindFrameAnchors):
    """Applies the V-FRM-05 anchors to ``dcm_b_from_w`` once it exists.

    Reads its expected values from ``_WindFrameAnchors``, the same plain container the
    anchor class uses, so the two cannot drift apart. It deliberately does **not**
    inherit from the anchor TestCase: unittest would then re-collect all seven anchor
    tests here and skip them, reporting seven misleading skips for tests that are in
    fact running and passing in the class above.
    """

    def test_v_frm_05_implementation_case_a(self):
        self.assert_matrix(
            dcm_b_from_w(_A_ZERO, _B_30), self.CASE_A_DCM,
            "V-FRM-05 case A: dcm_b_from_w(0, 30 deg) must equal R_y(0) R_z(-30 deg).",
        )

    def test_v_frm_05_implementation_case_b(self):
        self.assert_matrix(
            dcm_b_from_w(_A_30, _B_60), self.CASE_B_DCM,
            "V-FRM-05 case B: dcm_b_from_w(30 deg, 60 deg) must equal "
            "R_y(30 deg) R_z(-60 deg).",
        )

    def test_v_frm_05_implementation_passive_direction(self):
        """v_B = T_BW v_W, checked on vectors whose images are independently known.

        Orthonormality would pass for the transpose; these vectors would not.
        """
        self.assert_vector(
            _matvec(dcm_b_from_w(_A_ZERO, _B_30), self.CASE_A_V_WIND),
            self.CASE_A_V_BODY,
            "V-FRM-05: positive sideslip must give a positive y_B component.",
        )
        self.assert_vector(
            _matvec(dcm_b_from_w(_A_30, _B_60), self.CASE_B_V_WIND),
            self.CASE_B_V_BODY,
            "V-FRM-05: air-relative velocity through the coupled case.",
        )
        self.assert_vector(
            _matvec(dcm_b_from_w(_A_30, _B_60), self.CASE_B_V_WIND_GENERAL),
            self.CASE_B_V_BODY_GENERAL,
            "V-FRM-05: a general wind-frame vector, exercising all nine entries.",
        )

    def test_v_frm_05_implementation_secondary_properties(self):
        """Finiteness, orthonormality and determinant +1 away from the anchor points.

        **Secondary properties, deliberately labelled as such.** They catch a NaN, a
        typo that breaks the rotation structure, or a scaling error -- but they cannot
        distinguish the intended convention from its transpose, from the superseded F-2
        form, or from the reversed composition order: all four of those are orthonormal
        with determinant +1. The literal and vector anchors above remain the correctness
        evidence; these only extend coverage to angles the anchors do not visit.
        """
        for alpha_deg, beta_deg in ((0.0, 0.0), (-15.0, 40.0),
                                    (75.0, -80.0), (10.0, 5.0)):
            with self.subTest(alpha_deg=alpha_deg, beta_deg=beta_deg):
                dcm = _rows(dcm_b_from_w(math.radians(alpha_deg),
                                         math.radians(beta_deg)))
                for i in range(3):
                    for j in range(3):
                        self.assertTrue(
                            math.isfinite(dcm[i][j]),
                            f"V-FRM-05: entry [{i}][{j}] is not finite.",
                        )
                product = [[sum(dcm[i][k] * dcm[j][k] for k in range(3))
                            for j in range(3)] for i in range(3)]
                self.assert_matrix(
                    product, [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]],
                    "V-FRM-05 (secondary): T_BW must be orthonormal.",
                )
                det = (dcm[0][0] * (dcm[1][1] * dcm[2][2] - dcm[1][2] * dcm[2][1])
                       - dcm[0][1] * (dcm[1][0] * dcm[2][2] - dcm[1][2] * dcm[2][0])
                       + dcm[0][2] * (dcm[1][0] * dcm[2][1] - dcm[1][1] * dcm[2][0]))
                self.assertAlmostEqual(
                    det, 1.0, places=12,
                    msg="V-FRM-05 (secondary): determinant must be +1. A determinant "
                        "of -1 would mean a reflection, not a rotation.",
                )

    def test_v_frm_05_implementation_is_not_the_superseded_convention(self):
        """Explicit guard against a regression to the pre-audit form."""
        actual = _rows(dcm_b_from_w(_A_30, _B_60))
        self.assertGreater(
            _max_abs_diff(actual, self.CASE_B_DCM_SUPERSEDED), 1.7,
            "V-FRM-05: the implementation matches the SUPERSEDED R_y(-a)R_z(b) form "
            "(audit finding F-2). Both angle senses are inverted.",
        )
        self.assertGreater(
            _max_abs_diff(actual, self.CASE_B_DCM_REVERSED_ORDER), 0.4,
            "V-FRM-05: the implementation matches R_z(-b)R_y(a) -- correct factors, "
            "reversed composition order.",
        )


if __name__ == "__main__":
    unittest.main(verbosity=2)
