"""V-FRM-08 and V-ATT-01 — independent, hand-computed frame and attitude anchors.

WHY THIS FILE EXISTS BEFORE THE IMPLEMENTATION
----------------------------------------------
The pre-implementation mathematical audit
(``docs/research/PRE_IMPLEMENTATION_MATHEMATICAL_AUDIT.md``) found a sign error in the
wind-frame composition, ``T_BW = R_y(-alpha) R_z(beta)``, that had been published in
RS-001 and had passed a quality gate.  It would have reversed every sideslip-dependent
side force and yawing moment.

The important part is *how it survived*: the round-trip test specified for it,
V-FRM-05, would have passed, because a builder and an extractor written to agree with
each other round-trip perfectly whether or not either is right.  A **uniformly applied
wrong convention is self-consistent**, and self-consistency is what most tests measure.

Only an expected value obtained from *outside* the implementation can catch that class
of error.  Hence this file, written before ``radius/frames/`` exists: every expected
value below is derived by hand from ``docs/methodology/NOTATION_AND_CONVENTIONS.md``
and encoded as a literal.  Nothing here is produced by the code under test.

RULES THIS FILE OBEYS (from the Phase 2A brief, and from the audit's findings)
-----------------------------------------------------------------------------
* No expected value is generated by the implementation.
* No test is a round trip only.
* ``T @ T.T == I`` is never the sole evidence of correctness — a wrong convention is
  orthonormal too.
* No comparison of one implementation path against another that shares a convention.
  Where two paths (Euler and quaternion) are both checked, each is compared against the
  *same hand-derived literal*, not against each other.
* Tolerance is justified in ``TOL`` below, not chosen to make anything pass.

CONVENTIONS ENCODED (authoritative source: docs/methodology/NOTATION_AND_CONVENTIONS.md)
----------------------------------------------------------------------------------------
* SI units; angles in radians internally.
* Frames: ``I`` = flat-Earth NED inertial (x North, y East, **z Down**);
  ``B`` = body (x forward, y right, z down).  Both right-handed.
* Transformations are **passive**, read "to <- from":  ``v_B = T_b_from_i @ v_I``.
* Euler 3-2-1:  ``T_b_from_i(phi, theta, psi) = R_x(phi) R_y(theta) R_z(psi)`` with

      R_x(a) = [[1,0,0], [0, cos a, sin a], [0, -sin a, cos a]]
      R_y(a) = [[cos a, 0, -sin a], [0,1,0], [sin a, 0, cos a]]
      R_z(a) = [[cos a, sin a, 0], [-sin a, cos a, 0], [0,0,1]]

* Quaternion: **Hamilton product, scalar-first**, ``quat = (q0, q1, q2, q3)``,
  meaning ``quat_b_from_i``.
* Quaternion composition order is the **reverse** of matrix order (audit finding F-4):
  ``T(qa (x) qb) = T(qb) T(qa)``.
* ``T_b_from_i(quat)`` is defined for **non-unit** quaternions by dividing by
  ``quat . quat`` (audit finding F-3, assumption ``A-NUM-05``).

STATUS
------
Nothing is implemented.  These tests skip until ``radius.frames`` exists.  That is the
intended state: the anchors are recorded first so the implementation is written against
a specification it cannot quietly redefine.

The API names below are this file's *proposal*, consistent with the naming rules in
NOTATION_AND_CONVENTIONS.md section 8.  If Phase 2B chooses different names, update the
imports — but **the numerical anchors must not change**.  A failing anchor means the
implementation is wrong, or the convention has been deliberately changed via an ADR and
this file is stale.  It never means the anchor should be adjusted to fit.

DEMONSTRATED TO HAVE TEETH
--------------------------
A suite that only skips proves nothing, and a suite that passes under a wrong
convention is worse than none.  Before this file was committed it was run against
throwaway implementations carrying deliberate, individually injected convention errors
(mutation testing, 2026-09-09; harness kept out of the repository as a scratch
artifact).  Result: the correct implementation passed all 13 tests, and every one of
the following was caught —

    active/T_i_from_b instead of passive T_b_from_i ....... 16 failures
    scalar-LAST quaternion ordering ....................... 7 failures
    sign error in R_y (the -sin(theta) entry) ............. 3 failures
    3-2-1 Euler factors composed in reverse order ......... 2 failures
    reversed quaternion product order (audit F-4) ......... 1 failure
    missing /(quat.quat) for non-unit quaternions (F-3) ... 1 failure

The last two are caught by exactly one test each, which is the intended design: they
are the dedicated anchors for those findings.  If either of those tests is ever
weakened, the corresponding audit finding loses its only guard.

HOW TO RUN — and one command that must NOT be used
--------------------------------------------------
Standard library only; pytest is not a project dependency and is not installed.

From the repository root::

    python -m unittest discover -s tests -t tests

**Do not use ``python tests/test_frames.py``.**  Running the file as a script puts
``tests/`` on ``sys.path`` rather than the repository root, so ``import radius`` fails,
every test skips, and unittest prints ``OK (skipped=13)``.  That reads as success while
having verified nothing — the precise failure mode this file exists to prevent.  The
``__main__`` block below is retained only for use with the repository root already on
``PYTHONPATH``.

(``discover -s tests -t .`` is unavailable: Python 3.11+ requires the start directory to
be importable, which would mean adding ``tests/__init__.py``.  That has not been done,
because the command above works without it.)
"""

import math
import unittest

# --------------------------------------------------------------------------------------
# Implementation under test.  Absent by design during Phase 2A.
# --------------------------------------------------------------------------------------
try:  # pragma: no cover - exercised only once radius/ exists
    from radius.frames import (
        dcm_b_from_i_euler,   # (phi_rad, theta_rad, psi_rad) -> 3x3, rows indexable
        dcm_b_from_i_quat,    # (quat scalar-first, possibly non-unit) -> 3x3
        quat_b_from_i_euler,  # (phi_rad, theta_rad, psi_rad) -> 4, scalar-first
    )
    from radius.math.quaternion import quat_multiply  # Hamilton, scalar-first

    _IMPL_AVAILABLE = True
    _SKIP_REASON = ""
except ImportError as _exc:  # expected during Phase 2A
    _IMPL_AVAILABLE = False
    _SKIP_REASON = (
        "radius.frames / radius.math.quaternion not implemented yet (Phase 2A: anchors "
        f"are written before the implementation). Import error: {_exc}"
    )


# --------------------------------------------------------------------------------------
# Tolerance — justified, not tuned.
# --------------------------------------------------------------------------------------
# Every anchor below is O(1) in magnitude and reachable in O(10) floating-point
# operations, so the honest error budget is a few ULP, ~1e-16.  The one unavoidable
# contribution is the trig argument itself: cos(pi/2) evaluates to 6.1e-17, not to zero,
# so a strict equality test would fail for a *correct* implementation.
#
# 1e-12 leaves four orders of magnitude of headroom above that noise floor, which keeps
# the tests from being brittle across platforms and libm versions.
#
# It is nowhere near loose enough to hide the errors these tests exist to catch: a
# transposed matrix, a reversed composition order, an active-instead-of-passive rotation
# or a flipped sign all produce discrepancies of order 0.1 to 2.0 — ten to twelve orders
# of magnitude above this threshold.  The tolerance therefore separates "floating-point
# noise" from "wrong convention" by a margin that leaves no ambiguity.
TOL = 1e-12

SQRT2_2 = math.sqrt(2.0) / 2.0   # 0.70710678118654752
SQRT2_4 = math.sqrt(2.0) / 4.0   # 0.35355339059327376
SQRT3_2 = math.sqrt(3.0) / 2.0   # 0.86602540378443865
SQRT6_4 = math.sqrt(6.0) / 4.0   # 0.61237243569579452


# --------------------------------------------------------------------------------------
# Local helpers.  Deliberately dependency-free and independent of the code under test:
# a matrix-vector product written here cannot inherit a convention error from radius/.
# --------------------------------------------------------------------------------------
def _rows(matrix):
    """Return a 3x3 as a plain nested list, whatever container the implementation uses."""
    return [[float(matrix[i][j]) for j in range(3)] for i in range(3)]


def _matvec(matrix, vector):
    return [sum(float(matrix[i][k]) * vector[k] for k in range(3)) for i in range(3)]


def _transpose(matrix):
    return [[matrix[j][i] for j in range(3)] for i in range(3)]


def _max_abs_diff(a, b):
    return max(abs(a[i][j] - b[i][j]) for i in range(3) for j in range(3))


class _AnchorAssertions(unittest.TestCase):
    """Assertions that say *which convention error* a failure implies.

    A bare "matrices differ" failure sends the reader looking for an arithmetic slip.
    These messages name the specific misconvention whose signature the actual result
    matches, which is usually the whole diagnosis.
    """

    def assert_matrix(self, actual, expected, what):
        got = _rows(actual)
        if _max_abs_diff(got, expected) <= TOL:
            return

        diagnosis = ""
        if _max_abs_diff(_transpose(got), expected) <= TOL:
            diagnosis = (
                "\n  DIAGNOSIS: the result is the TRANSPOSE of the expected matrix. "
                "The implementation is producing T_i_from_b (or an active rotation) "
                "where the passive 'to <- from' convention requires T_b_from_i. "
                "See NOTATION_AND_CONVENTIONS.md section 4."
            )
        self.fail(
            f"{what}\n"
            f"  expected: {expected}\n"
            f"  actual:   {got}\n"
            f"  max |diff| = {_max_abs_diff(got, expected):.3e} (tol {TOL:.0e})"
            f"{diagnosis}"
        )

    def assert_vector(self, actual, expected, what):
        got = [float(x) for x in actual]
        worst = max(abs(g - e) for g, e in zip(got, expected))
        if worst <= TOL:
            return
        self.fail(
            f"{what}\n  expected: {expected}\n  actual:   {got}\n"
            f"  max |diff| = {worst:.3e} (tol {TOL:.0e})"
        )


# ======================================================================================
# V-FRM-08 — 90 degree yaw convention anchor
# ======================================================================================
@unittest.skipUnless(_IMPL_AVAILABLE, _SKIP_REASON)
class TestVFRM08YawConvention(_AnchorAssertions):
    """V-FRM-08: the single hand-computed anchor that pins the yaw convention.

    HAND DERIVATION (no implementation involved)
    --------------------------------------------
    With phi = theta = 0 and psi = 90 deg, the 3-2-1 composition collapses to
    T_b_from_i = R_z(pi/2).  Substituting cos(pi/2) = 0 and sin(pi/2) = 1 into the
    documented R_z:

        R_z(pi/2) = [[ 0, 1, 0],
                     [-1, 0, 0],
                     [ 0, 0, 1]]

    PHYSICAL CROSS-CHECK (an independent route to the same answer)
    --------------------------------------------------------------
    The rows of T_b_from_i are the body axes expressed in inertial components.  After a
    +90 deg yaw the nose points East, so x_B = (0,1,0) = row 0.  The right wing then
    points South, so y_B = (-1,0,0) = row 1.  Yaw does not tilt the vehicle, so
    z_B = (0,0,1) = row 2.  This agrees with the matrix above, derived two different
    ways.

    WHAT THIS CATCHES
    -----------------
    * Active/passive inversion, and T_i_from_b returned where T_b_from_i was asked for:
      both give the transpose, which sends x_I to +y_B instead of -y_B.
    * A sign error in R_z.
    * An ENU (z-up) frame substituted for NED.
    * A left-handed axis set.

    None of these is detectable by orthonormality or by a round trip: the transpose of a
    rotation is a perfectly good rotation, and round-trips through it are exact.
    """

    def setUp(self):
        self.T = dcm_b_from_i_euler(0.0, 0.0, math.pi / 2.0)

    def test_v_frm_08_x_inertial_maps_to_minus_y_body(self):
        # The anchor named in the audit: +x_I -> -y_B.
        self.assert_vector(
            _matvec(self.T, [1.0, 0.0, 0.0]),
            [0.0, -1.0, 0.0],
            "V-FRM-08: a North-pointing inertial unit vector must appear along -y_B "
            "after a +90 deg yaw. A result of (0,+1,0) means the transformation is "
            "being applied in the wrong direction.",
        )

    def test_v_frm_08_remaining_basis_vectors(self):
        # y_I (East) lies along the nose after a +90 deg yaw; z_I is untouched by yaw.
        self.assert_vector(
            _matvec(self.T, [0.0, 1.0, 0.0]), [1.0, 0.0, 0.0],
            "V-FRM-08: +y_I (East) must map to +x_B after a +90 deg yaw.",
        )
        self.assert_vector(
            _matvec(self.T, [0.0, 0.0, 1.0]), [0.0, 0.0, 1.0],
            "V-FRM-08: +z_I (Down) is invariant under yaw.",
        )

    def test_v_frm_08_asymmetric_vector(self):
        # Basis vectors alone cannot separate every sign error, because each exercises
        # one column.  (3,4,5) has three distinct non-zero components, so a swapped or
        # mis-signed entry anywhere in the matrix changes the answer.
        # By hand: row0.v = 4, row1.v = -3, row2.v = 5.
        self.assert_vector(
            _matvec(self.T, [3.0, 4.0, 5.0]), [4.0, -3.0, 5.0],
            "V-FRM-08: hand-computed transform of an asymmetric vector.",
        )

    def test_v_frm_08_full_matrix(self):
        self.assert_matrix(
            self.T,
            [[0.0, 1.0, 0.0],
             [-1.0, 0.0, 0.0],
             [0.0, 0.0, 1.0]],
            "V-FRM-08: T_b_from_i(0, 0, 90 deg) must equal the hand-derived R_z(pi/2).",
        )


# ======================================================================================
# V-ATT-01 — hand-computed attitude / DCM anchors
# ======================================================================================
@unittest.skipUnless(_IMPL_AVAILABLE, _SKIP_REASON)
class TestVATT01AttitudeAnchors(_AnchorAssertions):
    """V-ATT-01: hand-derived DCMs for attitudes of increasing structure.

    Each expected matrix below was obtained by substituting exact trigonometric values
    into the elementary matrices documented in NOTATION_AND_CONVENTIONS.md section 4 and
    multiplying by hand.  The quaternion anchors were obtained by writing out the
    Hamilton product term by term.

    Where both the Euler path and the quaternion path are checked, each is compared
    against the *same hand-derived literal* — never against the other.  Two
    implementation paths that share a convention error agree with each other perfectly.
    """

    # -- Case 1: zero attitude -----------------------------------------------------
    def test_v_att_01_case1_identity_attitude(self):
        """Weak on its own, but it is the case that fails loudly if angle arguments are
        transposed in the signature (phi/theta/psi order) *and* a non-zero default is
        ever introduced. Kept as the base of the ladder."""
        identity = [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]
        self.assert_matrix(
            dcm_b_from_i_euler(0.0, 0.0, 0.0), identity,
            "V-ATT-01 case 1: zero attitude must give the identity DCM.",
        )
        self.assert_vector(
            quat_b_from_i_euler(0.0, 0.0, 0.0), [1.0, 0.0, 0.0, 0.0],
            "V-ATT-01 case 1: zero attitude must give the identity quaternion "
            "(1,0,0,0) in scalar-first ordering. A result of (0,0,0,1) means the "
            "implementation is scalar-LAST, which is a different convention.",
        )
        self.assert_matrix(
            dcm_b_from_i_quat([1.0, 0.0, 0.0, 0.0]), identity,
            "V-ATT-01 case 1: identity quaternion must give the identity DCM.",
        )

    # -- Case 2: principal-axis rotations -------------------------------------------
    #
    # Hand derivation, substituting cos(pi/2)=0, sin(pi/2)=1:
    #   roll  90:  R_x(pi/2) = [[1,0,0],[0,0,1],[0,-1,0]]
    #   pitch 90:  R_y(pi/2) = [[0,0,-1],[0,1,0],[1,0,0]]
    #   yaw   90:  R_z(pi/2) = [[0,1,0],[-1,0,0],[0,0,1]]
    #
    # Quaternions, from q = (cos(angle/2), axis * sin(angle/2)) with angle = pi/2:
    #   roll  90:  (sqrt2/2, sqrt2/2, 0, 0)
    #   pitch 90:  (sqrt2/2, 0, sqrt2/2, 0)
    #   yaw   90:  (sqrt2/2, 0, 0, sqrt2/2)
    #
    # These three are what isolate a single mis-signed elementary matrix. R_y carries the
    # -sin in its [0][2] entry where R_x and R_z carry +sin in [1][2] and [0][1]; that
    # asymmetry is real and is the most commonly mis-transcribed of the three.

    PRINCIPAL_CASES = (
        ("roll 90 deg", (math.pi / 2.0, 0.0, 0.0),
         [[1.0, 0.0, 0.0], [0.0, 0.0, 1.0], [0.0, -1.0, 0.0]],
         [SQRT2_2, SQRT2_2, 0.0, 0.0]),
        ("pitch 90 deg", (0.0, math.pi / 2.0, 0.0),
         [[0.0, 0.0, -1.0], [0.0, 1.0, 0.0], [1.0, 0.0, 0.0]],
         [SQRT2_2, 0.0, SQRT2_2, 0.0]),
        ("yaw 90 deg", (0.0, 0.0, math.pi / 2.0),
         [[0.0, 1.0, 0.0], [-1.0, 0.0, 0.0], [0.0, 0.0, 1.0]],
         [SQRT2_2, 0.0, 0.0, SQRT2_2]),
    )

    def test_v_att_01_case2_principal_axis_euler(self):
        for name, angles, expected, _quat in self.PRINCIPAL_CASES:
            with self.subTest(case=name):
                self.assert_matrix(
                    dcm_b_from_i_euler(*angles), expected,
                    f"V-ATT-01 case 2 ({name}): hand-derived elementary DCM. "
                    "A failure on pitch alone points at the -sin(theta) entry of R_y.",
                )

    def test_v_att_01_case2_principal_axis_quaternion(self):
        for name, angles, expected, quat in self.PRINCIPAL_CASES:
            with self.subTest(case=name):
                # Both paths are checked against the SAME hand literal, so a shared
                # convention error cannot cancel out between them.
                self.assert_vector(
                    quat_b_from_i_euler(*angles), quat,
                    f"V-ATT-01 case 2 ({name}): hand-derived quaternion, scalar-first.",
                )
                self.assert_matrix(
                    dcm_b_from_i_quat(quat), expected,
                    f"V-ATT-01 case 2 ({name}): the hand-derived quaternion must "
                    "produce the hand-derived DCM.",
                )

    # -- Case 3: combined attitude, integer entries, pins composition ORDER ----------
    #
    # yaw 90 deg then pitch 90 deg (phi = 0):
    #   T = R_y(pi/2) R_z(pi/2)
    #     = [[0,0,-1],[0,1,0],[1,0,0]] @ [[0,1,0],[-1,0,0],[0,0,1]]
    #     = [[0,0,-1],[-1,0,0],[0,1,0]]      (multiplied out by hand)
    #
    # Physical cross-check: after a +90 deg yaw the nose is East and the right wing
    # South; pitching +90 deg about that (South-pointing) body y-axis lifts the nose to
    # Up and swings the belly-down axis round to East. So the body axes in inertial
    # components are x_B = Up = (0,0,-1), y_B = South = (-1,0,0), z_B = East = (0,1,0) —
    # exactly the rows above, reached without touching the matrices.
    COMBINED_ANGLES = (0.0, math.pi / 2.0, math.pi / 2.0)
    COMBINED_DCM = [[0.0, 0.0, -1.0], [-1.0, 0.0, 0.0], [0.0, 1.0, 0.0]]
    COMBINED_QUAT = [0.5, -0.5, 0.5, 0.5]

    def test_v_att_01_case3_combined_euler(self):
        self.assert_matrix(
            dcm_b_from_i_euler(*self.COMBINED_ANGLES), self.COMBINED_DCM,
            "V-ATT-01 case 3: hand-multiplied R_y(90) R_z(90). A failure here with "
            "case 2 passing means the 3-2-1 factors are being composed in the wrong "
            "order.",
        )

    def test_v_att_01_case3_combined_quaternion_composition_order(self):
        """This is the case that pins audit finding F-4.

        Quaternion composition is the REVERSE of matrix composition:
        T(qa (x) qb) = T(qb) T(qa).  To build T = R_y R_z we therefore need
        qa = q_yaw and qb = q_pitch, i.e. quat = q_yaw (x) q_pitch.

        Hand-computed Hamilton product, with H = sqrt(2)/2:
            q_yaw   = (H, 0, 0, H)
            q_pitch = (H, 0, H, 0)
            scalar  = H*H - (0,0,H).(0,H,0)          = 0.5 - 0    =  0.5
            vector  = H*(0,H,0) + H*(0,0,H) + (0,0,H) x (0,H,0)
                    = (0, 0.5, 0) + (0, 0, 0.5) + (-0.5, 0, 0)
                    = (-0.5, 0.5, 0.5)
            quat    = (0.5, -0.5, 0.5, 0.5)

        The reversed order gives (0.5, +0.5, 0.5, 0.5) — the x component flips sign —
        whose DCM is [[0,1,0],[0,0,1],[1,0,0]], a completely different attitude.  So
        this test discriminates the two orders rather than merely exercising one.
        """
        quat = quat_multiply([SQRT2_2, 0.0, 0.0, SQRT2_2],   # q_yaw
                             [SQRT2_2, 0.0, SQRT2_2, 0.0])   # q_pitch
        self.assert_vector(
            quat, self.COMBINED_QUAT,
            "V-ATT-01 case 3: hand-computed Hamilton product q_yaw (x) q_pitch. A "
            "result of (0.5, +0.5, 0.5, 0.5) means the product operands are being "
            "applied in the reversed (JPL-style) order.",
        )
        self.assert_matrix(
            dcm_b_from_i_quat(quat), self.COMBINED_DCM,
            "V-ATT-01 case 3: the composed quaternion must give the same hand-derived "
            "DCM as the Euler route.",
        )
        self.assert_vector(
            quat_b_from_i_euler(*self.COMBINED_ANGLES), self.COMBINED_QUAT,
            "V-ATT-01 case 3: Euler-to-quaternion must agree with the hand-computed "
            "Hamilton product.",
        )

    # -- Case 4: asymmetric combined attitude, exact surds --------------------------
    #
    # yaw 45 deg, pitch 30 deg, roll 0.  T = R_y(30) R_z(45), multiplied out by hand
    # from cos30 = sqrt3/2, sin30 = 1/2, cos45 = sin45 = sqrt2/2:
    #
    #   T = [[ sqrt6/4,  sqrt6/4, -1/2   ],
    #        [-sqrt2/2,  sqrt2/2,  0     ],
    #        [ sqrt2/4,  sqrt2/4,  sqrt3/2]]
    #
    # Every 90 deg case above has entries in {0, +-1}, which makes several distinct
    # misconventions produce matrices that are permutations of one another and can mask
    # each other.  This case has six distinct irrational magnitudes, is not symmetric
    # (T[0][2] = -0.5 while T[2][0] = +0.354), and therefore separates a transposed
    # result from a correct one on magnitude alone — not merely on sign.
    ASYMMETRIC_ANGLES = (0.0, math.radians(30.0), math.radians(45.0))
    ASYMMETRIC_DCM = [
        [SQRT6_4, SQRT6_4, -0.5],
        [-SQRT2_2, SQRT2_2, 0.0],
        [SQRT2_4, SQRT2_4, SQRT3_2],
    ]

    def test_v_att_01_case4_asymmetric_euler(self):
        self.assert_matrix(
            dcm_b_from_i_euler(*self.ASYMMETRIC_ANGLES), self.ASYMMETRIC_DCM,
            "V-ATT-01 case 4: hand-multiplied R_y(30) R_z(45). Distinct irrational "
            "entries make a transposition detectable by magnitude, not just by sign.",
        )

    def test_v_att_01_case4_asymmetric_quaternion(self):
        # Same literal, reached through the quaternion representation.
        self.assert_matrix(
            dcm_b_from_i_quat(quat_b_from_i_euler(*self.ASYMMETRIC_ANGLES)),
            self.ASYMMETRIC_DCM,
            "V-ATT-01 case 4: the quaternion route must reproduce the same "
            "hand-derived DCM as the Euler route.",
        )

    # -- Quaternion argument handling, anchored to case 2's literal ------------------
    #
    # Both sub-cases below are anchored to the hand-derived R_z(pi/2) literal, so
    # neither is a round trip or a self-consistency check.  They cover the subset of
    # audit findings F-3 (A-NUM-05) and the double-cover property that a literal DCM
    # already pins; the dedicated V-FRM-09 and V-FRM-10 anchors are a later increment.

    YAW90_QUAT = [SQRT2_2, 0.0, 0.0, SQRT2_2]
    YAW90_DCM = [[0.0, 1.0, 0.0], [-1.0, 0.0, 0.0], [0.0, 0.0, 1.0]]

    def test_v_att_01_non_unit_quaternion(self):
        """A-NUM-05. RK stages necessarily evaluate the derivative at non-unit
        quaternions.  Because T(k*q) = k^2 T(q), an implementation that omits the
        division by quat.quat silently scales every force by ||quat||^2 inside stages
        2-4 of every step.  Scaling by 2 here makes that a factor of 4."""
        self.assert_matrix(
            dcm_b_from_i_quat([2.0 * x for x in self.YAW90_QUAT]), self.YAW90_DCM,
            "V-ATT-01 (A-NUM-05): a quaternion of norm 2 must give the same rotation "
            "as the unit quaternion. A result scaled by 4 means the division by "
            "quat.quat is missing.",
        )

    def test_v_att_01_negated_quaternion_double_cover(self):
        """quat and -quat are the same attitude; the DCM formula is quadratic in quat,
        so this must hold exactly rather than approximately."""
        self.assert_matrix(
            dcm_b_from_i_quat([-x for x in self.YAW90_QUAT]), self.YAW90_DCM,
            "V-ATT-01: negating a quaternion must not change the attitude it "
            "represents (double cover).",
        )


if __name__ == "__main__":
    unittest.main(verbosity=2)
